### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by lai-pf** [edward1997104/Neural-Template#2]
Hi,Edward. Thanks for sharing the code. And I want to know the training time and the gpu you used during training. 
Excellent work. thanks again.

**Comment by edward1997104** [comment]
As stated in the supp., the training of the auto-encoding task for the continuous and discrete phases in total takes around 7 days on a cluster of eight RTX3090 GPUs, and the training of the image encoder takes around 12 hours.
The training is slow mainly due to the numerical solver in the adjoint method, you might set a larger threshold (atol and rtol in config.py) to speed up the training process at the expense of some reconstruction quality.
